image: dolfinx/dolfinx:nightly

stages:
    - build
    # - test
    - deploy

build:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make -j4

deployToRadon:
    stage: deploy
    # only:
        # - master
    script:
        - eval `ssh-agent -s`
        - echo "SSH_DEPLOY_RADON" | tr -d '\r' | ssh-add -
        - ssh -p 19725 mleoni@radon1.ricam.oeaw.ac.at
        - kill $SSH_AGENT_PID
#
# deployToAtlas:
#     stage: deploy
#     only:
#         - master
#     script:
#         - eval `ssh-agent -s`
#         - echo "$SSH_DEPLOY_KEY" | tr -d '\r' | ssh-add -
#         - TERM=xterm ssh -o StrictHostKeyChecking=no -o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p mleoni@ac-01.sw.ehu.es" mleoni@atlas-fdr.sw.ehu.es
#         - kill $SSH_AGENT_PID
