image:
    name: dolfinx/dolfinx:nightly
    pull_policy: always

stages:
    - build
    # - test
    - deploy

build:
    stage: build
    script:
        - source /usr/local/bin/dolfinx-real-mode
        - export DOLFINX_DIR=/usr/local/dolfinx-real/lib/cmake/dolfinx
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make -j4

deployToRadon:
    stage: deploy
    only:
        - master
    script:
        - eval `ssh-agent -s`
        - echo "$SSH_DEPLOY_RADON" | tr -d '\r' | ssh-add -
        - ssh -tt -p 19725 -o StrictHostKeyChecking=no  mleoni@radon1.ricam.oeaw.ac.at
        - kill $SSH_AGENT_PID
