image: dolfinx/dolfinx:nightly

stages:
    - build
    # - test
    # - deploy

build:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make -j4
#
# deployToHipatia:
#     stage: deploy
#     only:
#         - master
#     script:
#         - eval `ssh-agent -s`
#         - echo "$SSH_DEPLOY_KEY" | tr -d '\r' | ssh-add -
#         - ssh -p 6556 -o StrictHostKeyChecking=no mleoni@hpc.bcamath.org
#         - kill $SSH_AGENT_PID
#
# deployToAtlas:
#     stage: deploy
#     only:
#         - master
#     script:
#         - eval `ssh-agent -s`
#         - echo "$SSH_DEPLOY_KEY" | tr -d '\r' | ssh-add -
#         - TERM=xterm ssh -o StrictHostKeyChecking=no -o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p mleoni@ac-01.sw.ehu.es" mleoni@atlas-fdr.sw.ehu.es
#         - kill $SSH_AGENT_PID
